### PR TITLE
Update parseCfg to 3.6.7

### PR DESCRIPTION
**Pull request by phako**
This is the latest version I could find. There is a 3.6.8a on the
website in archive.org, but the download is gone.

https://web.archive.org/web/20020220051615/http://www.enjoy.ne.jp/~gm/program/parsecfg/index.html

This version is from http://www.mentaljynx.com/CCpp/libs/parsecfg/parsecfg.tar

This should also fix a cuple of memory leaks

### CODE REVIEW

**Comment by Jeija** [comment]
From what you've seen, do you think we could just replace this whole parseCfg mess with [glib's config file parser](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html) instead without breaking people's old config files?
Honestly, even if it breaks some / all existing config files, I'd still consider switching to something else - after all, these configs are not like super complicated to restore...

**Comment by phako** [comment]
I tried that; there was one feature in parseCfg it didn't support and that was used. Sorry, I have to dig a bit deeper in my local branches if I still have it

**Comment by Jeija** [comment]
Hm, okay. It would be interesting to know which feature exactly isn't supported... If it's something minor, I wouldn't care too much.

**Comment by phako** [comment]
Thanks to git reflog I ressurected my change. The issue was macros, they are saved like this:

```
macros ·= <Primary>n::aaa
macros·= <Primary><Shift>b::klsjdlksjd\0
```

Which parsecfg makes into a list of those macros, but GKeyFile insists on unique keys. This is of course fixable, but would need some migration path for older configs.

You could have string lists in GKeyFile, but that would then somehow rule out the separator being in the macro.

Anyway, I have pushed what I had to https://github.com/phako/gtkterm/tree/wip/new-config

**Comment by Jeija** [comment]
Thank you very much for that information! For reference, [here](https://github.com/GNOME/glib/blob/master/glib/gkeyfile.c#L148) is the confirmation that glib ignores duplicate keys.

I don't know if any single person has a large amount of GTKTerm macros that couldn't just be quickly added back in if we break backwards compatibility... But even if we really want to stay backwards-compatible, it would certainly be feasible to add a function that, before opening the .gtktermrc file, quickly scans all lines, finds duplicate `macros` entries and merges them or something.
So I'd rather move over to glibs config file parser.

**Comment by wvdakker** [comment]
Hi, was there any progress on this PR?
I am converting to gtk4 and want to drop the parsecfg part.
Unfortunately I don't have a config file with macros :)

**Comment by phako** [comment]
I am still on parseCfg... The whole config handling is the one part in gtkterm's source that is really annoying

**Comment by wvdakker** [comment]
Agree,
We can dump parseCfg and provide a tool to do some kind of migration.
We have to find a solution for the macro's. But how hard can it be
....😎️

**Comment by phako** [comment]
I will have some time again to look into this after the current GNOME cycle, I have to finish my things in there first.

**Comment by Jeija** [comment]
> We can dump parseCfg and provide a tool to do some kind of migration.

I agree. I think at some point breaking backwards compatibility, even without a migration tool, is acceptable. I mean, most people's GTKTerm configurations are not that difficult to replicate in a new version.

**Comment by wvdakker** [comment]
Ok, I gone dump the parsecfg and replace it with GKeyFile.

**Comment by wvdakker** [comment]
@phako Can I 'borrow' your code as template? I will add a copyright refering to you in the file.

**Comment by phako** [comment]
Sure sure.

**Pull request closed without merging**
