### PR TITLE
solve timestamp issues with auto-crlf and add const specifier

### PR DESCRIPTION
**Pull request by ddmesh**
Hi, 

I have fixed a problem when timestamp was inserted and auto crlf is active.
It also fixes the "strange" newline when waiting for new data.
To ensure that incoming buffer parameters of some functions are never touched, I have added
const specifier. This should always be used to avoid accidental modification an memory corruptions.

BR
 Stephan

### CODE REVIEW

**Comment by ddmesh** [comment]
Hi, when do you merge my request? It solves some think that needed to be resoved. ;-)

**Comment by ddmesh** [comment]
since running ubuntu 18.04 automake api version needs to be updated.
I also addes some missing dependencies to README.md.

**Comment by ddmesh** [comment]
Hi, when do you merge my request? It solves some things that needed to be resolved. ;-)
Also how is your plan to release a new gtkterm version to debian/ubuntu repo? think the application got some improvements in meantime that are worth to ship.
New config or other features could come later easily.
byte
Stephan

**Comment by Jeija** [comment]
Sorry for not responding to your GitHub Pull Request for so long (I kind of accidentally found myself in the role of being the gtkterm maintainer and don't really have the time for it...) - but I'm planning to find some time for reviewing and possibly merging your code this weekend or at the latest next Monday. I also want to switch to the meson build system (already created a branch for that), so I'm not going to merge your automake-related changes.

Regarding the Debian / Ubuntu releases, @wvdakker is responsible for those. I'd be happy to increment the gtkterm version after switching to the meson build system and merging your PR (and others) though, if that's all that is needed for a new gtkterm build.

**Comment by wvdakker** [comment]
I think if we have a stable meson build system and a few issues are resolved (#22, #11) we can release and make a new Debian release.
I myself will take #22 and #11 for my account.

**Comment by Jeija** [comment]
I just merged this as 0fe04444559a78fbce79bd65e776ea1a9c742b6c. Functionally, 0fe04444559a78fbce79bd65e776ea1a9c742b6c does not change anything compared to this PR, I only I fixed some minor style issues (e.g. indentation tabs / spaces was inconsistent on a few lines).
I agree, timestamps and auto CR LF work so much better know :+1: 

So thank you very much for your contribution, and sorry again for taking so long to merge this.

**Comment by ddmesh** [comment]
Hi,

thanks for taking time and merging. ;-)
Byte
 Stephan

**Pull request closed without merging**
