### PR TITLE
Add support to find text

### PR DESCRIPTION
**Pull request by Lihis**

### CODE REVIEW

**Comment by Jeija** [comment]
Thanks for your PR :+1: 
Looks good at a first glance, I will look into this more closely some time in the coming days. In the meantime, if anyone has any comment, let me know.

From a UI design viewpoint, I am wondering if maybe we could have something that looks a bit more like what GNOME Terminal is doing, i.e., a text box with a magnifier class and up / down buttons to the right:
GNOME Terminal

It would be extra cool if instead of having a popup window, the search box could simply appear at the top of the window, the way GNOME web / Epiphany does it:
Screenshot from 2022-03-22 22-24-44

What do you think?

**Comment by Lihis** [comment]
Yes I agree that would be much better, I'll take a look on how to implement that.

**Comment by Lihis** [comment]
The search looks like this now:
gtkterm-search

Comments about the code would be nice :slightly_smiling_face: I tried to make it fit the existing coding style.

---

Going a bit offtopic but do you have thoughts of porting the application to GTK4?

**Comment by Jeija** [comment]
Thanks for your work, looks a lot better to me!
I added some additional improvements in https://github.com/Jeija/gtkterm/commit/1c1d4275ddb8e123485d088876793da2a5ad760e:

* Improve visual style: Pack up / down buttons with search box into a single rectangle with rounded corners (look closely to spot the difference :wink:  )
search buttons
* Closing the search toolbar by pressing Ctrl+Shift+F again was broken (you call `search_bar_show` instead of `search_bar_hide`)
* Add keybinding: Pressing escape closes search toolbar
* Add keybinding: Shift+Enter moves to previous search result (Enter moves to next search result, as previously)

Let me know if these changes sound good to you. 

> I tried to make it fit the existing coding style.

Oh dear :scream:... The coding style of GTKTerm is probably not something to look up to too much. The GTKTerm code is absolutely ancient (it dates back to before 2002), I think GTK+ 2.0 wasn't even out there back then. It awkwardly mixes French and English function and variable names. Overall, it doesn't exactly adhere to modern software design standards. But it works, GTKTerm has important features that people care about, so I guess it makes sense to maintain it. Maybe this also partially answers your question about GTK 4.0: A GTK 4.0 port would be nice, and I'm all for it if it doesn't require too much work, but there are all kinds of other issues that really should be fixed in the GTKTerm source code.

Some years ago I actually though about rewriting GTKTerm from scratch in Vala and started by targeting a specific niche application (a serial port terminal specifically for ESP8266 development), but I never really got around to work on it any further: https://github.com/Jeija/espterm

**Comment by Lihis** [comment]
Your changes looks good for me:

- The up/down buttons looks much better now (and more importantly, the same as in other applications)
- Good catch on the `search_bar_show` call, thanks
- The additional keybindings are nice.

> The coding style of GTKTerm is probably not something to look up to too much.

Haha :stuck_out_tongue: didn't know that this has been written so long time ago. But it works and I have been now happily using it for couple weeks, the only thing what I missed was the ability to search text.

Porting probably takes some work.. But is there a list of issues which should be fixed first?

**Comment by Jeija** [comment]
Perfect! I will see when I have some time to properly review the code in the next couple of days and maybe fix some minor style issues here and there, but otherwise, I don't see any reason not to merge this PR. Looking good :+1: 

> Porting probably takes some work.. But is there a list of issues which should be fixed first?

Some good places to start fixing problems:

* Fix all of the compile-time warnings. They are mostly related to GTKTerm using GTK functionality which has been deprecated with GTK+ 3. This is also a prerequisite for porting to GTK 4, since the deprecated functionality will most likely no longer exist there. This is definitely the most important one.
* Translate the remaining variable and function names from French to English. No more "fenetre", no more "ecriture" and so on. Makes it easier for other contributors.
* See if there is a better replacement for the parseCfg mess (related to https://github.com/Jeija/gtkterm/pull/23)
* Improve separation of concerns, modularization: Currently, there are function calls between modules all over the place, we should have a clear separation between modules.
* Fix minor style issues, e.g., function naming conventions (`function_name` instead of `functionName` or `FunctionName` or `Function_name`)

If you are interested in working on some of these, I'm very happy about pull requests!

**Comment by wvdakker** [comment]
> Porting probably takes some work.. But is there a list of issues which should be fixed first?

Perhaps we can make a feature list and attach it to some kind of releaseplanning (gitlab can do that, cant find it in github..).
I myself will work on compile warnings... and also a tabbed version would be nice.

**Comment by Lihis** [comment]
> Perfect! I will see when I have some time to properly review the code in the next couple of days and maybe fix some minor style issues here and there

Yeah, no hurry.

> Perhaps we can make a feature list and attach it to some kind of releaseplanning (gitlab can do that, cant find it in github..).

Or create issue per bullet point and link them to a "milestone". Maybe that would be equivalent of the Gitlab feature?

**Comment by wvdakker** [comment]
> Or create issue per bullet point and link them to a "milestone".
> Maybe that would be equivalent of the Gitlab feature?
> —

Sure also a possibility.

**Comment by Jeija** [comment]
Merged, finally! Sorry for the delay and thanks for your contribution.

Some minor enhancements I made before merging:
* Search is now case-insensitive
* After closing and then reopening the search bar, searching used to be broken, there were always no results (basically, `vte_regex_unref` needs to be called when closing the search bar). This is now fixed.

**Comment by Lihis** [comment]
No problem and thank you 👍

**Pull request merged**
