### PR TITLE
bugfixing and adding new functionality "timestamp"

### PR DESCRIPTION
**Pull request by ddmesh**
The version 1.0 had some issues that I have fixed.

- add user message when configuration could not be loaded/written. before there was no user
  message. If using an outdated configuration file with flags that are not supported, the whole
  configuration was droped. Use will now get a hint where to look at.
- increment version number and add some infos about modification and author

- fix loading configuration for some flags. Options were loaded but not set internally and in GUI.
- add loading/storing timestamp flag in configuration file
- fix illegal memory access: when enable CR/newline auto conversion local memory was already
  freed after leaving scope. Copy content of this memory was illegal memory access.
- add option to display timestamps
- change default baud to 115200, increment default scrollback lines to 3000; increment maximal 
  scrollback lines to 99999, because those values are much more useful then previous restrictions.

### CODE REVIEW

**Comment by wvdakker** [comment]
Hi Stephan,

Thanks for the contribution.
One remark, we are not yet at a 1.0 release.  There is one issue open (#11) before
we can make a 1.0 release and get it into Debian.
Please revert the increment of the version number.

/Willem

**Comment by ddmesh** [comment]
Hi Willem,

I can revert it, but it is strange because when I install gtkterm via ubuntu from normal package sources, gtkterm displays its version as 1.0.

Bye
 Stephan

**Comment by wvdakker** [comment]
Correct, the about-dialog gives 1.0. The official package install however gives a git-version of 0.99.7

**Comment by ddmesh** [comment]
Hi,
I have reverted all files that came in with "version number" and re-added my self as contributor to fill the list ;-)

Beside of this there is an other guy who has added some kind of "device monitor". Im not sure if this is finished and what this should do. Perhaps it solves the problem when a linux has open the terminal and then goes to standby. After waking up the terminal should reopen the serial port and continue. At moment I have to close the terminal and reopen it, which is quite annoying.
Perhaps it is easy to implement, or the guy with the device monitoring (https://github.com/kev1pic/gtkterm) ?

I'm not sure if all the auto generated make/config files must be included in this repository. I've seen 
that on each build those files gets updated. and because they belong to the git repo, any change would be commited. I thought there is only one or two files that defines the config. and autoconfig/m4 stuff would create those intermediate files.
Others that have forked this repo, do check in those files, too. when they create a pull request, then you as the maintainer has to verify those files or re-generating it and commit them. I think this is a bad solution.

Byte
 Stephan

**Comment by wvdakker** [comment]
I have merged your contribution.
There was already an autoreconnect branch and I have merge this into the master. It is working ok for autoreconnecting a device. 
Before the 1.0 release I will cleanup some (autogenerated) files.

Thanks for you contribution.

**Pull request merged**
